name: GuardianAC
version: 1.0.0
main: com.nasem.guardianac.GuardianAC
api-version: '1.21'
author: Nasem
description: Anti-Cheat plugin for Paper 1.21
depend: [packetevents]
commands:
  guardian:
    description: GuardianAC main command
    aliases: [gac, guardianac]
    usage: /guardian <subcommand>
permissions:
  guardianac.alerts:
    description: Receive anti-cheat alerts
    default: op
  guardianac.admin:
    description: Admin commands
    default: op
